/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,html}"],
  theme: {
    extend: {},
  },
  safelist: [
    "bg-white",
    "p-8",
    "rounded",
    "shadow-md",
    "w-96",
    "text-2xl",
    "font-semibold",
    "mb-6",
    "mb-4",
    "block",
    "bg-red-100",
    "text-gray-600",
    "text-sm",
    "font-medium",
    "mb-2",
    "w-full",
    "p-2",
    "border",
    " text-black-500 ",
    "focus:outline-none",
    "focus:border-blue-500",
    "email",
    "password",
    "bg-blue-500",
    "text-white",
    "py-2",
    "hover:bg-blue-600",
    "transition",
    "duration-300",
  ],
  plugins: [],
};
